
project_id = "uzktgfhnbiqbqfyohvan"

[api]
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
port = 54327

[functions.generate-content-ideas]
verify_jwt = false

[functions.get_server_timestamp]
verify_jwt = false

