workflows:
  capacitor-ios-app:
    name: Capacitor iOS App
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        NODE_VERSION: 20
        CAPACITOR_CLI_TELEMETRY_OPTOUT: 1
        # Code signing variables - you'll need to add these in Codemagic UI
        # XCODE_PROJECT: ios/App/App.xcodeproj
        # XCODE_SCHEME: App
        # BUNDLE_ID: com.lovable.app
      node: $NODE_VERSION
      xcode: latest
      cocoapods: default
    # Add code signing configuration at workflow level
    code_signing:
      - ios_development
      - ios_distribution
    cache:
      cache_paths:
        - $HOME/.npm
        - node_modules
        - ios/App/Pods
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
        - pattern: develop
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Install Capacitor CLI
        script: |
          npm install -g @capacitor/cli
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install iOS dependencies
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/App.xcarchive \
            clean archive
      - name: Create IPA file
        script: |
          cd ios/App
          echo "Current directory: $(pwd)"
          echo "Listing files in current directory:"
          ls -la
          echo "Listing files in ../../public/:"
          ls -la ../../public/
          cp ../../public/exportOptions.plist . || { echo "Copy failed"; exit 1; }
          echo "Listing files after copy:"
          ls -la
          xcodebuild -exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - ios/App/build/**/*.xcarchive
      - ios/App/build/**/*.ipa
      - build/**
      - dist/**
    publishing:
      # app_store_connect:
      #   # Configure App Store Connect publishing here when ready
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      email:
        recipients:
          - terri@becomingsupernova.com
        notify:
          success: true
          failure: true
