  - name: Sync Capacitor
    script: |
      npx cap sync ios
  - name: Clean iOS build
    script: |
      rm -rf ios/build
      rm -rf ~/Library/Developer/Xcode/DerivedData/*
  - name: Install iOS dependencies
    script: |
      cd ios
      pod install
  - name: Build iOS app
    script: |
      cd ios
      xcodebuild -workspace App.xcworkspace \
        -scheme App \
        -configuration Release \
        -destination generic/platform=iOS \
        -archivePath build/App.xcarchive \
        clean archive \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

  - name: Create IPA file
    script: |
      cd ios
      # Copy exportOptions.plist to the correct location if it doesn't exist
      if [ ! -f "exportOptions.plist" ]; then
        echo "Creating exportOptions.plist..."
        cat > exportOptions.plist << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>development</string>
	<key>teamID</key>
	<string>YOUR_TEAM_ID</string>
	<key>uploadBitcode</key>
	<false/>
	<key>uploadSymbols</key>
	<false/>
	<key>compileBitcode</key>
	<false/>
	<key>thinning</key>
	<string>&lt;none&gt;</string>
</dict>
</plist>
EOF
      fi
      xcodebuild -exportArchive \
        -archivePath build/App.xcarchive \
        -exportPath build/ \
        -exportOptionsPlist exportOptions.plist \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

  cache:
    cache_paths:
      - $HOME/.npm
      - node_modules
      - ios/Pods

  artifacts:
    - ios/build/**/*.xcarchive
    - ios/build/**/*.ipa
    - build/**
    - dist/** 