  - name: Sync Capacitor
    script: |
      npx cap sync ios
  - name: Clean iOS build
    script: |
      rm -rf ios/build
      rm -rf ~/Library/Developer/Xcode/DerivedData/*
  - name: Install iOS dependencies
    script: |
      cd ios
      pod install
  - name: Build iOS app
    script: |
      cd ios
      xcodebuild -workspace App.xcworkspace \
        -scheme App \
        -configuration Release \
        -destination generic/platform=iOS \
        -archivePath build/App.xcarchive \
        clean archive \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

  - name: Create IPA file
    script: |
      cd ios
      echo "Current directory: $(pwd)"
      echo "Copying exportOptions.plist from project root..."
      cp ../public/exportOptions.plist .
      echo "exportOptions.plist copied. Contents:"
      cat exportOptions.plist
      echo "File permissions:"
      ls -la exportOptions.plist
      echo "Running xcodebuild export..."
      xcodebuild -exportArchive \
        -archivePath build/App.xcarchive \
        -exportPath build/ \
        -exportOptionsPlist exportOptions.plist \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO \
        CODE_SIGNING_ALLOWED=NO

  cache:
    cache_paths:
      - $HOME/.npm
      - node_modules
      - ios/Pods

  artifacts:
    - ios/build/**/*.xcarchive
    - ios/build/**/*.ipa
    - build/**
    - dist/** 